/* eslint-disable */
/**
 * Generated `api` utility.
 *
 * THIS CODE IS AUTOMATICALLY GENERATED.
 *
 * Generated by convex@1.3.1.
 * To regenerate, run `npx convex dev`.
 * @module
 */

import type {
  ApiFromModules,
  FilterApi,
  FunctionReference,
} from "convex/server";
import type * as domain from "../domain";
import type * as http from "../http";
import type * as images from "../images";
import type * as messages from "../messages";
import type * as payments from "../payments";
import type * as stripe from "../stripe";
import type * as userApiLimit from "../userApiLimit";
import type * as users from "../users";

/**
 * A utility for referencing Convex functions in your app's API.
 *
 * Usage:
 * ```js
 * const myFunctionReference = api.myModule.myFunction;
 * ```
 */
declare const fullApi: ApiFromModules<{
  domain: typeof domain;
  http: typeof http;
  images: typeof images;
  messages: typeof messages;
  payments: typeof payments;
  stripe: typeof stripe;
  userApiLimit: typeof userApiLimit;
  users: typeof users;
}>;
export declare const api: FilterApi<
  typeof fullApi,
  FunctionReference<any, "public">
>;
export declare const internal: FilterApi<
  typeof fullApi,
  FunctionReference<any, "internal">
>;
